mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from notes import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path
from . import views
from .views import Home, MyPost, DetailPost, DetailPost1,CreatePost,UpdatePost,UpdatePost1,DeletePost,DeletePost1,LikeHome,LikeHome1, LikeDetail,LikeDetail1,FollowHome, FollowHome1,FollowDetail, FollowList,FollowList1,FollowGrade,CreatePost1,DetailPost,Math2Post,Math3Post,Math4Post,Ph2Post,Ph3Post,Ph4Post,LiPost,TePost,JaPost,En1Post,WePost,MtPost,PhPost,EcPost,UnPost,RiPost,TcPost,TePost,MaPost,ArPost,ItPost,SePost,Sc2Post,Sc3Post,Sc4Post,Ti2Post,Ti3Post,Ti4Post,Me2Post,Me3Post,Me4Post,De2Post,De3Post,De4Post,Tu2Post,Tu3Post,Tu4Post,Si2Post,Si3Post,Si4Post,Ke2Post,Ke3Post,Ke4Post,Ma2Post,Ma3Post,Ma4Post,Ou2Post,Ou3Post,Ou4Post,Su2Post,Su3Post,Su4Post,Jo2Post,Jo3Post,Jo4Post,Se2Post,Se3Post,Se4Post,Bu2Post,Bu3Post,Bu4Post,Do2Post,Do3Post,Do4Post,Yu2Post,Yu3Post,Yu4Post,En2Post,En3Post,En4Post,Sec2Post,Sec3Post,Sec4Post,OtherPost
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'notes'

urlpatterns = [
    path('', views.note_grade, name='home'),
    path('b1/', views.note_b1, name='b1'),
    path('b2/', views.note_b2, name='b2'),
    path('b3/', views.note_b3, name='b3'),
    path('b4/', views.note_b4, name='b4'),
    path('mypost/', MyPost.as_view(), name='mypost'),
    path('detail/<int:pk>/', DetailPost.as_view(), name='detail'),
    path('detail/<int:pk>/update/', UpdatePost.as_view(), name='update'),
    path('detail/<int:pk>/delete/', DeletePost.as_view(), name='delete'),
    path('detail1/<int:pk>/', DetailPost1.as_view(), name='detail1'),
    path('detail1/<int:pk>/update/', UpdatePost1.as_view(), name='update1'),
    path('detail1/<int:pk>/delete/', DeletePost1.as_view(), name='delete1'),
    path('create/', CreatePost.as_view(), name='create'),
    path('create1/', CreatePost1.as_view(), name='create1'),
    path('create_grade/',views.create_grade,name='create_grade'),
    path('like-home/<int:pk>/', LikeHome.as_view(), name='like-home'),
    path('like-home1/<int:pk>/', LikeHome1.as_view(), name='like-home1'),
    path('like-detail/<int:pk>/', LikeDetail.as_view(), name='like-detail'),
    path('like-detail1/<int:pk>/', LikeDetail1.as_view(), name='like-detail1'),
    path('follow-home/<int:pk>/', FollowHome.as_view(), name='follow-home'),
    path('follow-home1/<int:pk>/', FollowHome1.as_view(), name='follow-home1'),
    path('follow-detail/<int:pk>/', FollowDetail.as_view(), name='follow-detail'),
    path('follow-list/', FollowList.as_view(), name='follow-list'),
    path('follow-list1/', FollowList1.as_view(), name='follow-list1'),
    path('follow_grade/',views.FollowGrade,name='follow_grade'),
    path('detail/<int:pk>/liked/',views.note_like,name='note_like'),
    path('li/',LiPost.as_view(),name='li'),
    path('te/',TePost.as_view(),name='te'),
    path('ja/',JaPost.as_view(),name='ja'),
    path('en/',En1Post.as_view(),name='en1'),
    path('we/',WePost.as_view(),name='we'),
    path('mt/',MtPost.as_view(),name='mt'),
    path('ph/',PhPost.as_view(),name='ph'),
    path('ec/',EcPost.as_view(),name='ec'),
    path('un/',UnPost.as_view(),name='un'),
    path('ri/',RiPost.as_view(),name='ri'),
    path('tc/',TcPost.as_view(),name='tc'),
    path('ma/',MaPost.as_view(),name='ma'),
    path('ar/',ArPost.as_view(),name='ar'),
    path('it/',ItPost.as_view(),name='it'),
    path('se/',SePost.as_view(),name='se'),
    path('other/',OtherPost.as_view(),name='other'),
    path('math2/',Math2Post.as_view(),name='math2'),
    path('math3/',Math3Post.as_view(),name='math3'),
    path('math4/',Math4Post.as_view(),name='math4'),
    path('ph2/',Ph2Post.as_view(),name='ph2'),
    path('ph3/',Ph3Post.as_view(),name='ph3'),
    path('ph4/',Ph4Post.as_view(),name='ph4'),
    path('sc2/',Sc2Post.as_view(),name='sc2'),
    path('sc3/',Sc3Post.as_view(),name='sc3'),
    path('sc4/',Sc4Post.as_view(),name='sc4'),
    path('ti2/',Ti2Post.as_view(),name='ti2'),
    path('ti3/',Ti3Post.as_view(),name='ti3'),
    path('ti4/',Ti4Post.as_view(),name='ti4'),
    path('me2/',Me2Post.as_view(),name='me2'),
    path('me3/',Me3Post.as_view(),name='me3'),
    path('me4/',Me4Post.as_view(),name='me4'),
    path('de2/',De2Post.as_view(),name='de2'),
    path('de3/',De3Post.as_view(),name='de3'),
    path('de4/',De4Post.as_view(),name='de4'),
    path('tu2/',Tu2Post.as_view(),name='tu2'),
    path('tu3/',Tu3Post.as_view(),name='tu3'),
    path('tu4/',Tu4Post.as_view(),name='tu4'),
    path('si2/',Si2Post.as_view(),name='si2'),
    path('si3/',Si3Post.as_view(),name='si3'),
    path('si4/',Si4Post.as_view(),name='si4'),
    path('ke2/',Ke2Post.as_view(),name='ke2'),
    path('ke3/',Ke3Post.as_view(),name='ke3'),
    path('ke4/',Ke4Post.as_view(),name='ke4'),
    path('ma2/',Ma2Post.as_view(),name='ma2'),
    path('ma3/',Ma3Post.as_view(),name='ma3'),
    path('ma4/',Ma4Post.as_view(),name='ma4'),
    path('ou2/',Ou2Post.as_view(),name='ou2'),
    path('ou3/',Ou3Post.as_view(),name='ou3'),
    path('ou4/',Ou4Post.as_view(),name='ou4'),
    path('su2/',Su2Post.as_view(),name='su2'),
    path('su3/',Su3Post.as_view(),name='su3'),
    path('su4/',Su4Post.as_view(),name='su4'),
    path('jo2/',Jo2Post.as_view(),name='jo2'),
    path('jo3/',Jo3Post.as_view(),name='jo3'),
    path('jo4/',Jo4Post.as_view(),name='jo4'),
    path('se2/',Se2Post.as_view(),name='se2'),
    path('se3/',Se3Post.as_view(),name='se3'),
    path('se4/',Se4Post.as_view(),name='se4'),
    path('bu2/',Bu2Post.as_view(),name='bu2'),
    path('bu3/',Bu3Post.as_view(),name='bu3'),
    path('bu4/',Bu4Post.as_view(),name='bu4'),
    path('do2/',Do2Post.as_view(),name='do2'),
    path('do3/',Do3Post.as_view(),name='do3'),
    path('do4/',Do4Post.as_view(),name='do4'),
    path('yu2/',Yu2Post.as_view(),name='yu2'),
    path('yu3/',Yu3Post.as_view(),name='yu3'),
    path('yu4/',Yu4Post.as_view(),name='yu4'),
    path('en2/',En2Post.as_view(),name='en2'),
    path('en3/',En3Post.as_view(),name='en3'),
    path('en4/',En4Post.as_view(),name='en4'),
    path('sec2/',Sec2Post.as_view(),name='sec2'),
    path('sec3/',Sec3Post.as_view(),name='sec3'),
    path('sec4/',Sec4Post.as_view(),name='sec4'),
]

notes/views.py
from django.shortcuts import render,redirect,resolve_url
from django.http import HttpResponse
from django.urls import path
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Post,Connection,Post1,Connection1
from django.urls import reverse_lazy
from django.views import View
from django.views import generic



# Create your views here.

class Home(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'list.html'
    def get_queryset(self):
        return Post.objects.exclude(user=self.request.user).order_by('-created_at1'),
      
   
class MyPost(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'list.html'

    def get_context_data(self, **kwargs):
        context = super(MyPost, self).get_context_data(**kwargs)
        context.update({
            'object_list2': Post1.objects.filter(user=self.request.user).order_by('-created_at1'),
        })
        return context
    
    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by('-created_at')







class DetailPost(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'detail.html'


class DetailPost1(LoginRequiredMixin, DetailView):
    model = Post1
    template_name = 'detail1.html'


class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'create.html'
    fields = ['title','content','grade','sub','file']
    success_url = reverse_lazy('notes:mypost')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class CreatePost1(LoginRequiredMixin, CreateView):
    model = Post1
    template_name = 'create1.html'
    fields = ['title1','content1','sub1','file']
    success_url = reverse_lazy('notes:mypost')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



def create_grade(request):
    return render(request,'create_grade.html')





    

class UpdatePost(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'update.html'
    fields = ['title', 'content']

    def get_success_url(self,  **kwargs):
        pk = self.kwargs["pk"]
        return reverse_lazy('notes:detail', kwargs={"pk": pk})
   
    def test_func(self, **kwargs):
        pk = self.kwargs["pk"]
        post = Post.objects.get(pk=pk)
        return (post.user == self.request.user)


class UpdatePost1(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post1
    template_name = 'update1.html'
    fields = ['title1', 'content1']

    def get_success_url(self,  **kwargs):
        pk = self.kwargs["pk"]
        return reverse_lazy('notes:detail1', kwargs={"pk": pk})
   
    def test_func(self, **kwargs):
        pk = self.kwargs["pk"]
        post = Post1.objects.get(pk=pk)
        return (post.user == self.request.user)

        


class DeletePost(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'delete.html'
    success_url = reverse_lazy('notes:mypost')
    
    def test_func(self, **kwargs):
        pk = self.kwargs["pk"]
        post = Post.objects.get(pk=pk)
        return (post.user == self.request.user)


class DeletePost1(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post1
    template_name = 'delete1.html'
    success_url = reverse_lazy('notes:mypost')
    
    def test_func(self, **kwargs):
        pk = self.kwargs["pk"]
        post = Post1.objects.get(pk=pk)
        return (post.user == self.request.user)
        



class LikeBase(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        related_post = Post.objects.get(pk=pk)
       
        if self.request.user in related_post.like.all(): 
            obj = related_post.like.remove(self.request.user)
        else:                         
            obj = related_post.like.add(self.request.user)
        return obj


class LikeBase1(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        related_post1 = Post1.objects.get(pk=pk)
       
        if self.request.user in related_post1.like1.all(): 
            obj = related_post1.like1.remove(self.request.user)
        else:                         
            obj = related_post1.like1.add(self.request.user)
        return obj


class LikeHome(LikeBase):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return redirect('notes:mypost')

class LikeHome1(LikeBase1):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return redirect('notes:mypost')


class LikeDetail(LikeBase,View):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs['pk'] 
        return redirect('notes:detail', pk)
        
class LikeDetail1(LikeBase,View):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs['pk'] 
        return redirect('notes:detail1', pk) 


class FollowBase(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        target_user = Post.objects.get(pk=pk).user
       
        my_connection = Connection.objects.get_or_create(user=self.request.user)
       
        if target_user in my_connection[0].following.all():
            obj = my_connection[0].following.remove(target_user)
        else:
            obj = my_connection[0].following.add(target_user)
        return obj

class FollowBase1(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        target_user = Post1.objects.get(pk=pk).user
       
        my_connection = Connection1.objects.get_or_create(user=self.request.user)
       
        if target_user in my_connection[0].following.all():
            obj = my_connection[0].following.remove(target_user)
        else:
            obj = my_connection[0].following.add(target_user)
        return obj


class FollowHome(FollowBase):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return redirect('notes:home')

class FollowHome1(FollowBase1):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return redirect('notes:home')

class FollowDetail(FollowBase):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs['pk'] 
        return redirect('notes:detail', pk)

class FollowDetail1(FollowBase1):
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs['pk'] 
        return redirect('notes:detail1', pk) 

class FollowList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'follow-list.html'

    def get_queryset(self):
        my_connection = Connection.objects.get_or_create(user=self.request.user)
        all_follow = my_connection[0].following.all()

        return Post.objects.filter(user__in=all_follow).order_by('-created_at')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['connection'] = Connection.objects.get_or_create(user=self.request.user)
        return context

    

class FollowList1(LoginRequiredMixin, ListView):
    model = Post1
    template_name = 'follow-list1.html'

    def get_queryset(self):
        my_connection = Connection1.objects.get_or_create(user=self.request.user)
        all_follow = my_connection[0].following.all()

        return Post1.objects.filter(user__in=all_follow).order_by('-created_at1')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['connection'] = Connection1.objects.get_or_create(user=self.request.user)
        return context



def FollowGrade(request):
    return render(request,'follow_grade.html')  


def note_like(request,pk):
    notes = Post.objects.get(pk=pk)
    notes.liked += 1 
    notes.save() 
    return redirect('notes:detail', pk)



class LiPost(LoginRequiredMixin, ListView):
    model = Post1
    template_name = 'list_sel.html'

    def get_context_data(self, **kwargs):
        context = super(LiPost, self).get_context_data(**kwargs)
        context.update({
            'object_list': Post1.objects.filter(sub1="1").order_by('-created_at1'),
        })
        return context


class OtherPost(LoginRequiredMixin, ListView):
    model = Post1
    template_name = 'list_sel.html'

    def get_context_data(self, **kwargs):
        context = super(OtherPost, self).get_context_data(**kwargs)
        context.update({
            'object_list': Post1.objects.filter(sub1="17").order_by('-created_at1'),
        })
        return context

class En1Post(LoginRequiredMixin, ListView):
    model = Post1
    template_name = 'list_sel.html'

    def get_context_data(self, **kwargs):
        context = super(En1Post, self).get_context_data(**kwargs)
        context.update({
            'object_list': Post1.objects.filter(sub1="2").order_by('-created_at1'),
        })
        return context

class JaPost(LoginRequiredMixin, ListView):
    model = Post1
    template_name = 'list_sel.html'

    def get_context_data(self, **kwargs):
        context = super(JaPost, self).get_context_data(**kwargs)
        context.update({
            'object_list': Post1.objects.filter(sub1="3").order_by('-created_at1'),
        })
        return context

class TePost(LoginRequiredMixin, ListView):
    model = Post1
    template_name = 'list_sel.html'

    def get_context_data(self, **kwargs):

notes/templates/create_grade.html
{% extends 'base.html' %}
{% load static %}

...

{% block content %}
<div class="container mt-3">
    <h2><a href="{% url 'notes:create1' %}">1学年</a></h2>
    <h2><a href="{% url 'notes:create' %}">2学年以降</a></h2>
</div>
{% endblock content %}

notes/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container">
   <div class="alert alert-success" role="alert">
      <p>タイトル：{{object.title}}</p>
      <p>投稿者：{{object.user}}</p>
      <p>授業日：{{object.day}}</p>
      <p>コメント：{{object.content}}</p>
      <p><a href="{{ object.file.url }}" target="_blank"><img src="{{ object.file.url }}" width="300" alt="" border="0"></a></p>
      <p><h5>画像をクリックで拡大</h5></p>
      <p>投稿日：{{object.created_at}}</p>
      {% if object.user == request.user %}
      <a href="{% url 'notes:update' object.pk %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">編集</a>
      <a href="{% url 'notes:delete' object.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">削除</a>
      {% endif %}
      
      {% if request.user in object.like.all %}
      <a href="{% url 'notes:like-detail' object.pk %}" class="like-btn add-color" tabindex="-1" role="button" aria-disabled="true"><i class="fas fa-heart"></i>♡</a>{{object.like.count}}
      {% else %}
      <a href="{% url 'notes:like-detail' object.pk %}" class="like-btn" tabindex="-1" role="button" aria-disabled="true"><i class="far fa-heart"></i>♡</a>{{object.like.count}}
      {% endif %}


      {% if object.user in connection.0.following.all %}
      <a href="{% url 'notes:follow-detail' object.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー解除</a>
      {% else %}
      <a href="{% url 'notes:follow-detail' object.pk %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー</a>
      {% endif %}  

      
      
   </div>
</div>

{% endblock content %}

notes/templates/follow-list1.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container mt-3">
   <div class="alert alert-success" role="alert">

   {% for item in object_list %}
   <div class="alert alert-success" role="alert">
       <p>タイトル：<a href="{% url 'notes:detail1' item.pk %}">{{item.title1}}</a></p>
       <p>投稿者：{{item.user.username}}</p>
       <p>授業日：{{item.day1}}</p>
       
       
       
       {% if request.user in item.like.all %}
       <a href="{% url 'notes:like-home' item.pk %}" class="like-btn add-color" tabindex="-1" role="button" aria-disabled="true"><i class="fas fa-heart"></i>♡</a>{{item.like1.count}}
       {% else %}
       <a href="{% url 'notes:like-home' item.pk %}" class="like-btn" tabindex="-1" role="button" aria-disabled="true"><i class="far fa-heart"></i>♡</a>{{item.like1.count}}
       {% endif %}  

       {% if item.user in connection.0.following.all %}
       <a href="{% url 'notes:follow-home' item.id %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー解除</a>
       {% else %}
       <a href="{% url 'notes:follow-home' item.id %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー</a>
       {% endif %}
       <img src="{{ item.file.url }}" width="193" height="130">
   </div>
   {% endfor %}

   
</div>
{% endblock content %}

notes/templates/home.html
{% extends 'base.html' %}
{% load static %}

...

{% block content %}
<div class="container mt-3">
   <h2><a href="{% url 'notes:b1' %}">1学年</a></h2>
       
       
       

</div>
{% endblock content %}

notes/templates/note_b1.html
{% extends 'base.html' %}
{% load static %}

...

{% block content %}
<div class="container">
    <h2><a href="{% url 'notes:li' %}">文系教養科目</a></h2>
    <h2><a href="{% url 'notes:en1' %}">英語科目</a></h2>
    <h2><a href="{% url 'notes:mt' %}">数学科目</a></h2>
    <h2><a href="{% url 'notes:ph' %}">物理科目</a></h2>
    <h2><a href="{% url 'notes:ec' %}">生命科学</a></h2>
    <h2><a href="{% url 'notes:un' %}">宇宙地球科学</a></h2>
    <h2><a href="{% url 'notes:other' %}">その他の理系科目</a></h2>
    <h2><a href="{% url 'notes:ri' %}">初年次理学院専門科目</a></h2>
    <h2><a href="{% url 'notes:tc' %}">初年次工学院専門科目</a></h2>
    <h2><a href="{% url 'notes:ma' %}">初年次物質理工学院専門科目</a></h2>
    <h2><a href="{% url 'notes:ar' %}">初年次環境社会理工学院専門科目</a></h2>
    <h2><a href="{% url 'notes:it' %}">初年次情報理工学院専門科目</a></h2>
    <h2><a href="{% url 'notes:se' %}">初年次生命理工学院専門科目</a></h2>
    <h2><a href="{% url 'notes:ja' %}">日本・日本文化科目</a></h2>
    <h2><a href="{% url 'notes:te' %}">教職科目</a></h2>
    <h2><a href="{% url 'notes:we' %}">広域教養科目</a></h2>
</div>
{% endblock content %}

notes/templates/note_b3.html
{% extends 'base.html' %}
{% load static %}

...

{% block content %}
<div class="container"><h2>理学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:math3' %}">数学系</a></h4>
        <h4><a href="{% url 'notes:ph3' %}">物理系</a></h4>
        <h4><a href="{% url 'notes:sc3' %}">化学系</a></h4>
        <h4><a href="{% url 'notes:ti3' %}">地球惑星科学</a></h4>
    </div>
</div>
<div class="container"><h2>工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:me3' %}">機械系</a></h4>
        <h4><a href="{% url 'notes:de3' %}">電気電子系</a></h4>
        <h4><a href="{% url 'notes:tu3' %}">情報通信系</a></h4>
        <h4><a href="{% url 'notes:si3' %}">システム制御系</a></h4>
        <h4><a href="{% url 'notes:ke3' %}">経営工学系</a></h4>
    </div>
</div>
<div class="container"><h2>物質理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:ma3' %}">材料系</a></h4>
        <h4><a href="{% url 'notes:ou3' %}">応用化学系</a></h4>
    </div>
</div>
<div class="container"><h2>情報理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:su3' %}">数理・計算科学系</a></h4>
        <h4><a href="{% url 'notes:jo3' %}">情報工学系</a></h4>
    </div>
</div>
<div class="container"><h2>生命理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:se3' %}">生命理工学系</a></h4>
    </div>
</div>
<div class="container"><h2>環境社会理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:bu3' %}">建築系</a></h4>
        <h4><a href="{% url 'notes:do3' %}">土木・環境工学系</a></h4>
    </div>
</div>
<div class="container"><h2>その他</h2>
    <div class="container">
        <h4><a href="{% url 'notes:en3' %}">英語科目</a></h4>
        <h4><a href="{% url 'notes:sec3' %}">第二外国語</a></h4>
    </div>
</div>
{% endblock content %}

notes/templates/note_b4.html
{% extends 'base.html' %}
{% load static %}

...

{% block content %}
<div class="container"><h2>理学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:math4' %}">数学系</a></h4>
        <h4><a href="{% url 'notes:ph4' %}">物理系</a></h4>
        <h4><a href="{% url 'notes:sc4' %}">化学系</a></h4>
        <h4><a href="{% url 'notes:ti4' %}">地球惑星科学</a></h4>
    </div>
</div>
<div class="container"><h2>工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:me4' %}">機械系</a></h4>
        <h4><a href="{% url 'notes:de4' %}">電気電子系</a></h4>
        <h4><a href="{% url 'notes:tu4' %}">情報通信系</a></h4>
        <h4><a href="{% url 'notes:si4' %}">システム制御系</a></h4>
        <h4><a href="{% url 'notes:ke4' %}">経営工学系</a></h4>
    </div>
</div>
<div class="container"><h2>物質理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:ma4' %}">材料系</a></h4>
        <h4><a href="{% url 'notes:ou4' %}">応用化学系</a></h4>
    </div>
</div>
<div class="container"><h2>情報理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:su4' %}">数理・計算科学系</a></h4>
        <h4><a href="{% url 'notes:jo4' %}">情報工学系</a></h4>
    </div>
</div>
<div class="container"><h2>生命理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:se4' %}">生命理工学系</a></h4>
    </div>
</div>
<div class="container"><h2>環境社会理工学院</h2>
    <div class="container">
        <h4><a href="{% url 'notes:bu4' %}">建築系</a></h4>
        <h4><a href="{% url 'notes:do4' %}">土木・環境工学系</a></h4>
    </div>
</div>
<div class="container"><h2>その他</h2>
    <div class="container">
        <h4><a href="{% url 'notes:en4' %}">英語科目</a></h4>
        <h4><a href="{% url 'notes:sec4' %}">第二外国語</a></h4>
    </div>
</div>
{% endblock content %}